#配置端口号
server:
  port: 8081

mybatis:
  type-aliases-package: com.system.module1.entity    # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/**/*.xml                       # mapper映射文件
  configuration:
    map-underscore-to-camel-case: true  # 开启驼峰uName自动映射到u_name


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boot_module?useSSL=true&serverTimezone=UTC
    username: root
    password: 123456


logging:
  level:
    com.system.module1.dao: debug